### ISSUE TITLE
num-to-words bugs

### ISSUE THREAD

**Issue by daninnm** [KeelyHill/tuppers-formula#7]
In numtowords.js:
'sexquinquagintacent' occurs twice (10 ** 471)
10 ** 531 is not on the list
'duattuornonagint' should probably be 'quattuornonagint'

**Comment by esimonov** [comment]
Thank you for pointing this out.

**Comment by KeelyHill** [comment]
Duplicate fixed in #10.
I don't understand these well enough to fix, these huge numbers a silly and fun. It's more fun with accuracy, please feel free to submit pull request if you know how. Closing issue for now.

**Comment by KeelyHill** [comment]
Duplicate fixed in PR #10 .
Other names fixed in PR #8 

It's been while since I touched this project, thanks for the PR!
